### PR TITLE
./run script; python3; django 1.11.1

### PR DESCRIPTION
**Pull request by nottrobin**
Upgrade everything.

Also make the `./run` script directly ask for the credentials for the assets server to connect to.

Document this in the README.

QA
--

Try following the `README.md`.

### CODE REVIEW

**Comment by nottrobin** [comment]
[Add ./run script to assets manager](https://trello.com/c/1ETVyuUP/3344-add-.%2Frun-script-to-assets-manager)

**Comment by WillMoggridge** [comment]
After getting it started with the settings, it tries to connect to openid and on return has an error:
```
KeyError at /openid/complete/ 'request'
```

It also seems to need the RequestContext changing to a dict like the others

**Comment by nottrobin** [comment]
@WillMoggridge Works for me. Could you try again? Check you ticked the box.

**Comment by WillMoggridge** [comment]
Ah, that is an interesting point. The group checkbox doesn't appear for me. Looking at why not...

**Comment by WillMoggridge** [comment]
I can't seem to get that checkbox to appear. If I remove `OPENID_LAUNCHPAD_TEAMS_REQUIRED` in the settings, I can log in. I can also log in to the live site as well. I am a bit confused by this.

I did realise that setting the api to `localhost` won't work. I couldn't seem to work out setting the Docker host API easily, maybe we need to work on that. This is definitely not a blocker, though.

Otherwise it is looking good.

**Pull request merged**
