### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by WillMoggridge**
Travis should run for this PR. Check the CI output results to verify.

This is waiting on the run script PR

### CODE REVIEW

**Comment by nottrobin** [comment]
Fixes https://github.com/ubuntudesign/web-squad/issues/22

**Comment by anthonydillon** [comment]
@WillMoggridge The CI is failing but not sure why? Nothing outputted from the sass lint.

**Comment by nottrobin** [comment]
@anthonydillon If you run `./run test` locally you'll probably understand why.

To test, it needs to connect to an assets server, I think. We either need to make it so the test doesn't try to connect to anything, or find a way to give Travis confidential credentials to connect to the staging assets server.

**Comment by anthonydillon** [comment]
I am struggling to run this project locally.

```bash
./run test
yarn install v0.24.4
warning ubuntu-website@0.0.1: License should be a valid SPDX license expression
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.57s.
Unable to find image 'yarn:latest' locally
docker: Error response from daemon: pull access denied for yarn, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by WillMoggridge** [comment]
As we talked about, I am going to close this PR for now and we will add a bigger CI improvement task to our backlog.

**Pull request closed without merging**
